website/models.py
from . import db
from flask_login import UserMixin
from sqlalchemy.sql import func

class Networks(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    network_id = db.Column(db.Integer)
    network_name = db.Column(db.String(100))
    host = db.Column(db.String(100))
    username = db.Column(db.String(100))
    password = db.Column(db.String(100))
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))

class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(150), unique=True)
    password = db.Column(db.String(150))
    networks = db.relationship('Networks')
    

website/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from os import path
from flask_login import LoginManager
from flask_session import Session

db = SQLAlchemy()
DB_NAME = "database.db"

def create_app():
    app = Flask(__name__)
    app.config['SECRET_KEY'] = 'secretkey'
    app.config['SQLALCHEMY_DATABASE_URI'] = f'sqlite:///{DB_NAME}'
    db.init_app(app)

    app.config["SESSION_PERMANENT"] = False
    app.config["SESSION_TYPE"] = "filesystem"
    Session(app)

    from .views import views
    from .auth import auth
    from .network_managing import network

    app.register_blueprint(views, url_prefix='/')
    app.register_blueprint(auth, url_prefix='/')
    app.register_blueprint(network, url_prefix='/networks')

    from .models import User, Networks
    

    with app.app_context():
        db.create_all()

    login_manager = LoginManager()
    login_manager.login_view = 'auth.login'
    login_manager.init_app(app)

    @login_manager.user_loader
    def load_user(id):
        return User.query.get(int(id))

    return app

website/auth.py
from flask import Blueprint, render_template, request, flash, redirect, url_for
from .models import User
from werkzeug.security import generate_password_hash, check_password_hash
from . import db
from flask_login import login_user, login_required, logout_user, current_user
from sqlalchemy import func

auth = Blueprint('auth', __name__)

@auth.route('/login', methods=['GET', 'POST'])
def login():
    
    if request.method != 'POST':
        return render_template('login.html', user=current_user)

    username = request.form.get('username')
    password = request.form.get('password')
    
    user = User.query.filter_by(username=username).first()
    
    if user:
        if check_password_hash(user.password, password):
            flash('Logget ind!', category='success')
            login_user(user, remember=True)
            return redirect(url_for('views.home'))
        else:
            flash('Forkert adgangskode', category='error')
    else:
        flash('Bruger eksisterer ikke', category='error')

    return render_template('login.html', user=current_user)

    

@auth.route('/logout')
@login_required
def logout():
    logout_user()
    flash('Logged out.')
    return redirect(url_for('auth.login'))

@auth.route('/register', methods=['GET', 'POST'])
def register():

    if request.method != 'POST':
        return render_template('register.html', user=current_user)
    
    username = request.form.get('username')
    password1 = request.form.get('password1')
    password2 = request.form.get('password2')
    
    user = User.query.filter_by(username=username).first()


    if user:
        flash('Brugernavn findes allerede.', category='error')
    elif len(username) < 4:
        flash('Username must be greater than 3 characters. Brugernavn er for kort', category='error')
    elif password1 != password2:
        flash('Adgangskoderne matcher ikke', category='error')
    elif len(password1) < 7:
        flash('Adgangskode er for kort', category='error')
    else:
        new_user = User(username=username, password=generate_password_hash(password1, method='pbkdf2'))
        db.session.add(new_user)
        db.session.commit()
        login_user(new_user, remember=True)

        flash('Account created!', category='success')
        return redirect(url_for('views.home'))
    
    return render_template('register.html', user=current_user)

    

website/views.py
from flask import Blueprint, render_template, request, flash, jsonify, redirect, url_for, session
from flask_login import login_required, current_user
from .models import Networks
from . import db
import json
from netmiko import ConnectHandler

views = Blueprint('views', __name__)

@views.route('/')
@login_required
def home():
    return render_template('home.html', user=current_user)


@views.route('/networks', methods=['GET', 'POST'])
@login_required
def networks():

    if request.method == 'POST':

        if request.form.get('change_button'):
            network_id = request.form['change_button']
            session["network_id"] = network_id
            return redirect(url_for('network.edit_network'))
        
        if request.form.get('connect_button'):
            network_id = request.form['connect_button']
            session["network_id"] = network_id
            network = Networks.query.filter_by(user_id=current_user.id, network_id=network_id).first()
            host = network.host
            username = network.username
            password = network.password

            
            try:
                connection = ConnectHandler(host=host, port=22,
                                        username=username, password=password,
                                        device_type='cisco_ios')
                output = connection.send_command('sh ip int brief')

                print(output)
                return redirect(url_for('network.connect'))
            
            except:
                flash('Can\'t connect', category='error')
                return redirect(url_for('network.connect'))

        if request.form.get('access_button'):

            network_id = request.form['access_button']
            session["network_id"] = network_id
            session["extended_access"] = 'False'

            return redirect(url_for('network.access_list'))
        
        if request.form.get('vlan_button'):

            network_id = request.form['vlan_button']
            session["network_id"] = network_id
            network = Networks.query.filter_by(user_id=current_user.id, network_id=network_id).first()
            host = network.host
            username = network.username
            password = network.password

            try:
                connection = ConnectHandler(host=host, port=22,
                                        username=username, password=password,
                                        device_type='cisco_ios')
                vlans = connection.send_command('sh vlan br')

                print(vlans)
                return redirect(url_for('network.vlans'))
            
            except:
                flash('Can\'t connect', category='error')

        
        if request.form.get('dhcp_button'):

            ### Netværk ###
            network_id = request.form['dhcp_button']
            session["network_id"] = network_id
            network = Networks.query.filter_by(user_id=current_user.id, network_id=network_id).first()
            host = network.host
            username = network.username
            password = network.password

            return redirect(url_for('network.dhcp'))

        if request.form.get('create_network_button'):
            return redirect(url_for('network.create_network'))
            
    return render_template('networks.html', user=current_user)

website/templates/access-list.html
{% extends "base.html" %}
{% block title %}Access Lists{% endblock %}
{% block content %}


<div class="dropdown container mt-5">
    <form method="POST">

        <button type="submit" class="btn btn-primary" name="extended_button" value="extended_button">Extended</button>
        <button type="submit" class="btn btn-primary" name="standard_button" value="standard_button">Standard</button>
        <br>

        <label for="access_list_name">Access List Name</label>
        <input type="text" name="access_list_name" id="access_list_name" class="form-control" value={% if access_list_name != None %} "{{ access_list_name }}" {% else %} "" {% endif %}>
        <br>
        
    
        <!--<label for="ip_or_port">Permit or deny</label>
        <select class="form-select" aria-label="Default select example" name="action">
            <option selected value="">Select</option>
            <option value="permit">Permit</option>
            <option value="deny">Deny</option>
        </select>-->
        
            <label for="permit_or_deny">Permit or deny</label>
            <select class="form-select" aria-label="Default select example" name="permit_or_deny">
                <option {% if permit_or_deny == None %} selected {% endif %} value=""></option>
                <option {% if permit_or_deny == 'permit' %} selected {% endif %} value="permit">Permit</option>
                <option {% if permit_or_deny == 'deny' %} selected {% endif %} value="deny">Deny</option>
            </select>
            <br>
        {% if extended == False %}
            <label for="any_or_host">Any or host</label>
            <select class="form-select" aria-label="Default select example" name="any_or_host">
                <option {% if any_or_host == None %} selected {% endif %} value=""></option>
                <option {% if any_or_host == 'any' %} selected {% endif %} value="any">Any</option>
                <option {% if any_or_host == 'host' %} selected {% endif %} value="host">Host</option>
            </select>
        
        <br>
        <label for="hostname">Hostname</label>
        <input type="text" name="hostname" id="hostname" class="form-control" value={% if hostname != None %}"{{ hostname }}" {% else %} "" {% endif %}>
        <br>
        {% endif %}
        
        
        {% if extended == True %}
            <label for="protocols">Protokoller</label>
            <select class="form-select" aria-label="Default select example" name="protocols" >
                
                <option {% if protocols == None %} selected {% endif %} value=""></option>
                <option {% if protocols == 'ahp' %} selected {% endif %} value="ahp">ahp</option>
                <option {% if protocols == 'eigrp' %} selected {% endif %} value="eigrp">eigrp</option>
                <option {% if protocols == 'gre' %} selected {% endif %} value="gre">gre</option>
                <option {% if protocols == 'icmp' %} selected {% endif %} value="icmp">icmp</option>
                <option {% if protocols == 'igmp' %} selected {% endif %} value="igmp">igmp</option>
                <option {% if protocols == 'ip' %} selected {% endif %} value="ip">ip</option>
                <option {% if protocols == 'ipinip' %} selected {% endif %} value="ipinip">ipinip</option>
                <option {% if protocols == 'nos' %} selected {% endif %} value="nos">nos</option>
                <option {% if protocols == 'ospf' %} selected {% endif %} value="ospf">ospf</option>
                <option {% if protocols == 'pcp' %} selected {% endif %} value="pcp">pcp</option>
                <option {% if protocols == 'pim' %} selected {% endif %} value="pim">pim</option>
                <option {% if protocols == 'tcp' %} selected {% endif %} value="tcp">tcp</option>
                <option {% if protocols == 'udp' %} selected {% endif %} value="udp">udp</option>
            </select>
            <br>
            <label for="custom_protocols">Tast selv protokol (0-255)</label>
            <input type="text" name="custom_protocols" id="custom_protocols" class="form-control" value={% if custom_protocols != None %} "{{ custom_protocols }}" {% else %} "" {% endif %}>
            <br>
            <label for="source">Source</label>
            <select class="form-select" aria-label="Default select example" name="source">
                <option {% if source == None %} selected {% endif %} value=""></option>
                <option {% if source == 'any' %} selected {% endif %} value="any">any</option>
                <option {% if source == 'host' %} selected {% endif %} value="host">host</option>
            </select>
            <br>
            <label for="destination">Destination</label>
            <select class="form-select" aria-label="Default select example" name="destination">
                <option {% if destination == None %} selected {% endif %} value=""></option>
                <option {% if destination == 'any' %} selected {% endif %} value="any">any</option>
                <option {% if destination == 'eq' %} selected {% endif %} value="eq">eq</option>
                <option {% if destination == 'gt' %} selected {% endif %} value="gt">gt</option>
                <option {% if destination == 'host' %} selected {% endif %} value="host">host</option>
                <option {% if destination == 'lt' %} selected {% endif %} value="lt">lt</option>
                <option {% if destination == 'neq' %} selected {% endif %} value="neq">neq</option>
                <option {% if destination == 'range' %} selected {% endif %} value="range">range</option>
            </select>
            <br>
            
            {% if destination == None %}  
                <button type="submit" class="btn btn-primary" name="next_button" value="next_button">Næste</button>
            
            {% elif destination == '' %}
            
            <label for="packet">Packet pis</label>
            <select class="form-select" aria-label="Default select example" name="packet">
                <option value=""></option>
                {% for packet in packet_list %}
                <option value="{{ packet }}">{{ packet }}</option>
                {% endfor %}

            </select>
            
            {% elif destination == 'host' %}
                
                <label for="host_pis">Host</label>
                <input type="text" name="host_pis" id="host_pis" class="form-control" value="">
            {% elif destination != 'any' or destination != 'host' %}
                <label for="port">Port (0-65535)</label>
                <input type="text" name="port" id="port" class="form-control" value="">
            
            {% endif %}
                <!--<label for="source_address">Port (0-65535)</label>
                <input type="text" name="source_address" id="source_address" class="form-control" value="">
                <br>-->
            
        {% endif %}
        <br>
        <button type="submit" class="btn btn-primary" name="save_button" value="save_button">Save</button>
    </form>
</div>


{% endblock %}

website/templates/base.html
<!DOCTYPE html>
<html>

<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <link rel="stylesheet" href="{{ url_for('static', filename='styles.css') }}">


    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link
        href="https://fonts.googleapis.com/css2?family=Lato:ital,wght@0,100;0,300;0,400;0,700;0,900;1,100;1,300;1,400;1,700;1,900&family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap"
        rel="stylesheet">

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">


    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
        crossorigin="anonymous"></script>

    <title>{% block title %}Title{% endblock %}</title>

</head>

<body>
    <div class="container">

        <ul class="nav justify-content-around">
            {% if user.is_authenticated %}
                <li class="nav-item nav-li">
                    <a class="nav-link nav-custom fw-bold" href="{{ url_for('views.home') }}">Hjem</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link nav-custom fw-bold" href="{{ url_for('views.networks') }}">Netværker</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link nav-custom fw-bold" href="{{ url_for('auth.logout') }}">Log ud</a>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link nav-custom fw-bold" href="{{ url_for('auth.login') }}">Login</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link nav-custom fw-bold" href="{{ url_for('auth.register') }}">Lav en bruger</a>
                </li>
            {% endif %}
        </ul>
    </div>

    {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
            {% for category, message in messages %}
                {% if category == 'error' %}
                    <div class="alert alert-danger alert-dismissible fade show" role="alert">
                        {{ message }}
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                    </div>
                {% else %}
                    <div class="alert alert-success alert-dismissible fade show" role="alert">
                        {{ message }}
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                    </div>
                {% endif %}
            {% endfor %}
        {% endif %}
    {% endwith %}
    <div class="container">
        {% block content %}
        {% endblock %}
    </div>
    

</body>


</html>

website/templates/dhcp.html
{% extends "base.html" %}
{% block title %}DHCP{% endblock %}
{% block content %}
<div class="container">
    <h1>DHCP</h1>
    <h3>Opsæt en DHCP-pool</h3>
    <form action="" method="POST" class="pe-2">
        <label for="dhcp_name">DHCP Navn</label>
        <input type="text" name="dhcp_name" id="dhcp_name" class="form-control">

        <label for="netværks_adresse">Netværks adresse</label>
        <input type="text" name="netværks_adresse" id="netværks_adresse" class="form-control">

        <label for="subnetmaske">Subnetmaske</label>
        <input type="text" name="subnetmaske" id="subnetmaske" class="form-control">

        <label for="router">Router</label>
        <select class="form-select" aria-label="Default select example" name="vlan">
            {% for i in range(10, 1001, 10) %}
            <option value="{{ i }}">{{ i }}</option>
            {% endfor %}
        </select>
        
        <label for="dns_server">DNS server</label>
        <input type="text" name="dns_server" id="dns_server" class="form-control">

        <button type="submit" class="btn btn-primary mt-2" name="create_button" value="create_button">Create</button>
    </form>
</div>
{% endblock %}

website/templates/home.html
{% extends "base.html" %}
{% block title %}Home{% endblock %}
{% block content %}
<h1 class="text-center fw-bold">Netværk automatisering</h1>
<h3 class="text-center">Lavet af Amalie, Arthur, Josephine og Mads</h3>
<img src="static/images/cisco.jpg" alt="Cisco" class="img-fluid rounded mx-auto d-block">
{% endblock %}

website/templates/login.html
{% extends "base.html" %}
{% block title %}Login{% endblock %}
{% block content %}
<form method="POST">
    <h3 align="center" class="fw-bold">Login</h3>
    <div class="mb-3">
        <label for="username">Brugernavn</label>
        <input type="username" name="username" id="username" class="form-control" placeholder="Enter username">
    </div>  
    <div class="mb-3">
        <label for="password">Password</label>
        <input type="password" name="password" id="password" class="form-control" placeholder="Password">
    </div>
    <button type="submit" class="btn btn-primary">Login</button>
</form>
{% endblock %}

website/templates/network_managing/access-list.html
{% extends "base.html" %}
{% block title %}Access Lists{% endblock %}
{% block content %}

<div class="back-div">
    <a class="back" href="{{ url_for('network.connect') }}">
        << Tilbage</a>
</div>
<h1 class="fw-bold text-center">Access lister</h1>
<div class="dropdown container mt-5 mb-3 manage p-4 rounded">
    <form method="POST">

        <button type="submit" class="btn btn-primary" name="extended_button" value="extended_button">Extended</button>
        <button type="submit" class="btn btn-primary" name="standard_button" value="standard_button">Standard</button>
        <br>

        <label for="access_list_name">Access List Name</label>
        <input type="text" name="access_list_name" id="access_list_name" class="form-control" value={% if
            access_list_name !=None %} "{{ access_list_name }}" {% else %} "" {% endif %}>
        <br>

        <label for="permit_or_deny">Permit or deny</label>
        <select class="form-select" aria-label="Default select example" name="permit_or_deny">
            <option {% if permit_or_deny==None %} selected {% endif %} value=""></option>
            <option {% if permit_or_deny=='permit' %} selected {% endif %} value="permit">permit</option>
            <option {% if permit_or_deny=='deny' %} selected {% endif %} value="deny">deny</option>
        </select>
        <br>

        {% if extended_access | default(False) %}
        <label for="protocols">Protokoller</label>
        <select class="form-select" aria-label="Default select example" name="protocols">

            <option {% if protocols==None %} selected {% endif %} value=""></option>
            {% for protokol in ['ahp', 'eigrp', 'gre', 'icmp', 'igmp', 'ip', 'ipinip', 'nos', 'ospf', 'pcp', 'pim',
            'tcp', 'udp'] %}
            <option {% if protocols==protokol %} selected {% endif %} value="{{ protokol }}">{{ protokol }}</option>
            {% endfor %}
        </select>
        <br>

        <label for="custom_protocols">Tast selv protokol (0-255)</label>
        <input type="text" name="custom_protocols" id="custom_protocols" class="form-control" value={% if
            custom_protocols !=None %} "{{ custom_protocols }}" {% else %} "" {% endif %}>
        <br>

        <label for="host_name">Hostname</label>
        <input type="text" name="host_name" id="host_name" class="form-control" value={% if host_name !=None
            %} "{{ host_name }}" {% else %} "" {% endif %}>
        <br>

        <label for="wildcard">Wildcard address</label>
        <input type="text" name="wildcard" id="wildcard" class="form-control" value={% if wildcard !=None
            %} "{{ wildcard }}" {% else %} "" {% endif %}>
        <br>

        <label for="source">Source</label>
        <select class="form-select" aria-label="Default select example" name="source">
            <option {% if source==None %} selected {% endif %} value=""></option>
            <option {% if source=='any' %} selected {% endif %} value="any">any</option>
            <option {% if source=='host' %} selected {% endif %} value="host">host</option>
        </select>


        {% else %}
        <label for="any_or_host">Any or host</label>
        <select class="form-select" aria-label="Default select example" name="any_or_host">
            <option {% if any_or_host==None %} selected {% endif %} value=""></option>
            <option {% if any_or_host=='any' %} selected {% endif %} value="any">Any</option>
            <option {% if any_or_host=='host' %} selected {% endif %} value="host">Host</option>
        </select>

        <br>
        <label for="hostname">Hostname</label>
        <input type="text" name="hostname" id="hostname" class="form-control" value={% if hostname !=None %}"{{ hostname
            }}" {% else %} "" {% endif %}>

        {% endif %}
        <br>
        <div class="form-check">
            <input class="form-check-input" type="checkbox" value="ja" name="ja_eller_nej" id="ja_eller_nej">
            <label class="form-check-label" for="ja_eller_nej">
                Skal 'permit ip any any' sættes ind til sidst?
            </label>
        </div>
        <br>
        <label for="interface">Placer ACL på interface</label>
        <select name="interface" id="interface" class="form-select">
            {% for interface in session["interfaces"] %}
            <option value="{{ interface['interface'] }}" {% if selected_interface==interface['interface'] %} selected {%
                endif %}>{{ interface['interface'] }}</option>
            {% endfor %}
        </select>
        <br>

        <label for="in_or_out">In eller out</label>
        <select name="in_or_out" id="in_or_out" class="form-select">
            {% for option in ['in', 'out'] %}
            <option value="{{ option }}" {% if selected_interface==option %} selected {% endif %}>{{ option }}</option>
            {% endfor %}
        </select>
        <br>


        <button type="submit" class="btn btn-primary" name="save_button" value="save_button">Lav</button>
    </form>
</div>


{% endblock %}

website/templates/network_managing/connect.html
{% extends "base.html" %}
{% block title %}Connect to network{% endblock %}
{% block content %}

<h1 class="fw-bold text-center">{{ network_name}}</h1>
<div class="mt-4 border rounded">
  <h3 class="text-center">Network information for {{ network_name }}</h3>
  <div class="row row-cols-2">
    <div class="col">
      <h2 class="text-center">Interfaces</h2>
      <div class="table-container table-scrollable">
        <table class="table table-striped">
          <thead>
            <tr>
              <th>Interface</th>
              <th>IP Address</th>
              <th>Status</th>
              <th>Protocol</th>
            </tr>
          </thead>
          <tbody>
            {% for interface in interfaces %}
            <tr>
              <td>{{ interface['interface'] }}</td>
              <td>{{ interface['ip_address'] }}</td>
              <td>{{ interface['status'] }}</td>
              <td>{{ interface['proto'] }}</td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>

    <div class="col">
      <h2 class="text-center">VLANS</h2>
      <div class="table-container table-scrollable">
        <table class="table table-striped">
          <thead>
            <tr>
              <th>VLAN</th>
              <th>Name</th>
              <th>Status</th>
              <th>Ports</th>
            </tr>
          </thead>
          <tbody>
            {% for vlan in vlans %}
            <tr>
              <td>{{ vlan['vlan_id'] }}</td>
              <td>{{ vlan['vlan_name'] }}</td>
              <td>{{ vlan['status'] }}</td>
              <td>{{ vlan['interfaces'] | join(', ') }}</td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

<div class="container border mt-3 mb-3 pb-3 rounded">
  <h3 class="text-center">Konfigurere</h3>
  <div class="">
    <form action="" method="POST" class="pe-2 d-flex justify-content-center">

      <button type="submit" class="btn btn-primary align-center m-2" name="hostname_button"
        value="{{ session['network_id'] }}">Skift hostname</button>

      <button type="submit" class="btn btn-primary align-center m-2" name="access_button"
        value="{{ session['network_id'] }}">Access List</button>

      <button type="submit" class="btn btn-primary align-center m-2" name="vlan_button"
        value="{{ session['network_id'] }}">VLANS</button>

      <button type="submit" class="btn btn-primary align-center m-2" name="dhcp_button"
        value="{{ session['network_id'] }}">DHCP</button>

      <button type="submit" class="btn btn-primary align-center m-2" name="ntp_server_button"
        value="{{ session['network_id'] }}">NTP Server</button>

      <button type="submit" class="btn btn-primary align-center m-2" name="ntp_klient_button"
        value="{{ session['network_id'] }}">NTP Klient</button>

      <button type="submit" class="btn btn-primary align-center m-2" name="port_sec_button"
        value="{{ session['network_id'] }}">Port security</button>

      <button type="submit" class="btn btn-success align-center m-2" name="gem_button"
        value="{{ session['network_id'] }}">Gem</button>
    </form>
  </div>
</div>

{% endblock %}

website/templates/network_managing/create_network.html
{% extends "base.html" %}
{% block title %}My networks{% endblock %}
{% block content %}
<h1 class="fw-bold text-center">Create network</h1>
<form method="POST">
    <div class="mb-3">
        <label for="network_name">Network name</label>
        <input type="network_name" name="network_name" id="network_name" class="form-control" placeholder="Enter network name">
    </div>
    <div class="mb-3">
        <label for="host">Host</label>
        <input type="host" name="host" id="host" class="form-control" placeholder="Enter host">
    </div>
    <div class="mb-3">
        <label for="username">Username</label>
        <input type="username" name="username" id="username" class="form-control" placeholder="Username">
    </div>
    <div class="mb-3">
        <label for="password">Password</label>
        <input type="text" name="password" id="password" class="form-control" placeholder="Password">
    </div>
    <button type="submit" class="btn btn-primary">Create</button>
</form>
{% endblock %}

website/templates/network_managing/dhcp.html
{% extends "base.html" %}
{% block title %}DHCP{% endblock %}
{% block content %}

<div class="back-div">
    <a class="back" href="{{ url_for('network.connect') }}"><< Tilbage</a>
</div>

<h1 class="fw-bold text-center">DHCP</h1>
<form action="" method="POST" class="pe-2">
    <h3>Lav DHCP pool</h3>
    <label for="dhcp_name">DHCP Navn</label>
    <input type="text" name="dhcp_name" id="dhcp_name" class="form-control">
    <br>

    <label for="netværks_adresse">Netværks adresse</label>
    <input type="text" name="netværks_adresse" id="netværks_adresse" class="form-control">
    <br>

    <label for="subnetmaske">Subnetmaske</label>
    <input type="text" name="subnetmaske" id="subnetmaske" class="form-control">
    <br>

    <label for="network">Defualt router</label>
    <input type="text" name="network" id="network" class="form-control">
    <br>

    <label for="exclude">Exclude address</label>
    <input type="text" name="exclude" id="exclude" class="form-control">
    <br>

    <button type="submit" class="btn btn-primary mt-2" name="create_button" value="create_button">Lav</button>
</form>

{% endblock %}